Simplify and Centralize `root_uri` and `built_in_slice_path`
zeroc-ice/vscode-slice pull request #30
Opened 2024-01-15 17:20 UTC by InsertCreativityHere

This PR centralizes the server-level config into their own struct: `ServerConfig`.
These fields are `root_uri` and `built_in_slice_path`.

And places an instance of this struct in a global `OnceLock`.
`OnceLock` has the semantics that it can only be set once, and is set atomically.

It also slightly tweaks how the `SliceConfig` caching works.
Now we update the cache when it's used, instead of whenever we change a value. This should trigger less cache updates.

----

Before this PR, we stored these fields directly in `Session`, behind `RwLocks`.
We also stored copies of these in every `SliceConfig`, but as bare values. All of these we redundant, and removed.

2024-01-15 18:30 UTC, InsertCreativityHere commented on server/src/main.rs
> +    SERVER_CONFIG.get().expect("server failed to initialized: `server_config` is unset!")
```suggestion
    SERVER_CONFIG.get().expect("server failed to initialize: `server_config` is unset!")
```

2024-01-15 18:31 UTC, InsertCreativityHere commented on server/src/main.rs
> +    pub fn initialize_server_config_from(params: tower_lsp::lsp_types::InitializeParams) {
This function is mostly a copy/paste from `session.rs`

2024-01-15 18:47 UTC, ReeceHumphreys requested changes
Im not sure if this will work in the long term. We need to switch to using `workspaceFolders` instead of the `rootUri` in the future. From a brief glance at the LSP spec it looks like `workspaceFolders` can change due to a `workspace/didChangeWorkspaceFolders` notification.

Maybe we should just once lock the built in slice path?

2024-01-16 15:24 UTC, InsertCreativityHere commented
> Im not sure if this will work in the long term

Well sure, this _exact_ structure won't work if we need to mutate the state in the future.
But when we get to that point, we can just move the locks inside. So, instead of `OnceLock<Config>` we'd just hold a `Config`, and each of it's fields would be locked individually.
Or, less elegant but even easier, we could change `OnceLock` to `RwLock` or `Mutex` or something.

But to me, that's future work, to be done when we add workspace folders.
Right now, as of this PR's opening, I believe `OnceLock` is the optimal choice.

2024-01-16 15:30 UTC, ReeceHumphreys commented
> But to me, that's future work, to be done when we add workspace folders. Right now, as of this PR's opening, I believe `OnceLock` is the optimal choice.

Right but that's work that we definitely want to do and somewhat soon. Im fine with this PR other than the `root_uri` change. I would rather preemptively assume that `root_uri` is going to be replaced with a mutable `workspaceFolders` rather than making this change just to undo it in a month or so.

>  So, instead of OnceLock<Config> we'd just hold a Config, and each of it's fields would be locked individually.

This is what I think this PR should do.

2024-01-16 15:59 UTC, InsertCreativityHere commented
> This is what I think this PR should do.

Okay, sure, that's fine with me.

2024-01-22 20:32 UTC, ReeceHumphreys commented
@InsertCreativityHere are you still planning on working on this PR or should we draft / close it for now?

2024-01-22 20:34 UTC, InsertCreativityHere commented
I'll know by tomorrow.
Now that #35 has been merged, I think I can do what this PR does, but without adding any global state.
But I haven't properly looked at that to make sure it's possible. If I'm wrong and I can't, I'll fall back to fixing this PR up.

2024-01-24 19:53 UTC, InsertCreativityHere commented
I'm pretty sure we can do this without a global variable.
Closing this in favor of a different approach I'll implement later.

2024-01-24 19:53 UTC, closed without merging